<?php

class MarkupSitemapXML extends WireData implements Module {

	/**
	 * Provide information about this module to ProcessWire
	 *
	 */
	public static function getModuleInfo() {
		return array(
			'title' => 'Markup Sitemap XML',
			'summary' => 'Generates an XML sitemap at yoursite.com/sitemap.xml for use with Google Webmaster Tools etc.',
			'href' => 'http://processwire.com/talk/index.php/topic,867.0.html',
			'version' => 105,
			'permanent' => false,
			'autoload' => true,
			'singular' => true,
			);
	}

	/**
	 * Add the hook
	 *
	 */
	public function init() {
		// Intercept a request for a root URL ending in sitemap.xml and output
		if (strpos($_SERVER['REQUEST_URI'],  '/sitemap.xml') !== FALSE) {
			$this->addHookAfter("Page::render",$this,"renderSitemap");
		}
	}

	public function renderSitemap(HookEvent $event){
			$event->replace = true;
			$lang = '';
			$this->pageselector = '';

			// support for LanguageLocalizedURL language module
			if(wire("modules")->isInstalled("LanguageLocalizedURL")) {
				$llu = wire("modules")->get("LanguageLocalizedURL");
				$lang = $this->user->language->name;
				if($lang == 'default') $lang = $llu->defaultLang;
				$langpage = $this->pages->get("/$lang/");
				if(!$langpage->id) throw new WireException("No language page found. You're using LanguageLocalizedURL, make sure the default language name is correct or if the /langname/ gateway page exist.");
				// get the field name for published language from the modules settings
				$publishedfield_name = $llu->publishedPageField ? $llu->publishedPageField : 'language_published';
				// add a selector to find children pages when generating sitemap list
				$this->pageselector = "$publishedfield_name=$langpage->id";
			}
			// Check for the cached sitemap, else generate and cache a fresh sitemap
			$cache =  wire('modules')->get("MarkupCache");
			if(!$output = $cache->get("MarkupSitemapXML$lang", 3600)) {
				$output = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n";
				$output .= '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">';
				$output .= $this->sitemapListPage(wire('pages')->get("/"));
				$output .= "\n</urlset>";
				$cache->save($output);
			}
			header("Content-Type: text/xml");
			$event->return = $output;
	}

	public function sitemapListPage($page) {
		$entry = "";
		if ($page->viewable() && ($page->sitemap_ignore == 0 || $page->path == '/')) { // $page->path part added so that it ignores hiding the homepage, else you wouldn't have ANY pages returned
			$modified = date ('Y-m-d', $page->modified);
			$entry = "\n  <url>\n";
			$entry .= "    <loc>{$page->httpUrl}</loc>\n";
			$entry .= "    <lastmod>{$modified}</lastmod>\n";
		  	$entry .= "  </url>";
		  	$children = $page->children($this->pageselector);
			if(count($children)) {
				foreach($children as $child) {
					$entry .= $this->sitemapListPage($child);
				}
			}
		}
		return $entry;
	}

	/**
	 * Install the module
	 *
	 */
	public function ___install() {

		if($this->fields->get('sitemap_ignore')) {
			$this->error("You already have a 'sitemap_ignore' field.");
			return;
		}

		wire('modules')->get('MarkupCache');

		$field = new Field();
		$field->type = $this->modules->get("FieldtypeCheckbox");
		$field->name = 'sitemap_ignore';
		$field->label = 'Hide page from XML sitemap';
		$field->description = 'Hide this page and its children from the XML sitemap';
		$field->save();

		$this->message("Added field 'sitemap_ignore'. Add this field to any templates where you want to prevent inclusion in the XML sitemap.");
	}

	/**
	 * Uninstall the module
	 *
	 */
	public function ___uninstall() {
		// only do the following if you want to uninstall the fields that were installed
		// this may be one thing that's safe to leave to the user
		$field = wire('fields')->get('sitemap_ignore');
		if($field && $field->numFieldgroups() > 0)
			throw new WireException("Can't uninstall because field sitemap_ignore is still being used. Please remove it from any templates.");
		wire('fields')->delete($field);
	}
}
